package encryption;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner s = new Scanner(System.in); // Initializing a scanner
        System.out.println("Hello there! Welcome to this encryption/decryption simulator. Please enter a text to encrypt: ");
        String text = s.nextLine(); // Reading a text from user

        String result = encrypted(text); // Initializing a variable that stores the encrypted text which is generated by calling to the encrypted method
        System.out.println("Here is your encrypted text: \n" + " **********  \n" + result + " " + " \n ********** \n");

        System.out.println("Would you like to decrypt your text? Please answer yes or no:");
        String answer = s.nextLine(); // Reading a text from user

        if (answer.equals("yes")) {
            System.out.println("Then enter a decrypted text please: ");
            String secondText = s.nextLine(); // Reading a text from user

            String result_decrypted = decrypted(secondText); // Initializing a variable that stores the decrypted text which is generated by calling to the decrypted method
            System.out.println("This is what the encrypted text was really saying: " + result_decrypted);
        }
        s.close(); // closing the scanner

    }

    public static String encrypted(String text) {

        char[][] encryption = { // creating a two-dimensional character array that stores how is every letter or a symbol is encrypted.
                {
                        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
                        'w', 'x', 'y', 'z', 'ä', 'ö', 'ü', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '#', '.', ',', '!', '?',
                },
                {
                        '?', '!', ',', '.', '#', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', 'ü', 'ö', 'ä', 'z', 'y', 'x', 'w',
                        'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a',
                },
        };


        char[] translation = text.toCharArray(); // Initializing a simple array of characters that stores the encrypted ("translated") text

        for (int k = 0; k < text.length(); k++) { // creating a loop that checks every character of the text given by user
            for (int j = 0; j < encryption[0].length; j++) {  // a second loop is going to check each character of the user text to find a match it to the characters of the first dimension of the encryption array
                if (text.charAt(k) == encryption[0][j]) { // if the chosen character has a match in the first dimension
                    translation[k] = encryption[1][j]; // the new value from the second dimension is assigned to it. The value of the second dimension has the same position that the first dimension character.
                }
            }
        }

        return new String(translation); // Returning a string that stores all the characters from the translation array. That prevents any mistakes passing a value of an array of characters.
    }

    public static String decrypted(String text) {

        char[][] encryption = { // creating a two-dimensional character array that stores how is every letter or a symbol is encrypted.
                {
                        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
                        'w', 'x', 'y', 'z', 'ä', 'ö', 'ü', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '#', '.', ',', '!', '?',
                },
                {
                        '?', '!', ',', '.', '#', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', 'ü', 'ö', 'ä', 'z', 'y', 'x', 'w',
                        'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a',
                },
        };


        char[] translation = text.toCharArray(); // Initializing a simple array of characters that stores the decrypted ("translated") text

        for (int k = 0; k < text.length(); k++) { // creating a loop that checks every character of the text given by user
            for (int j = 0; j < encryption[0].length; j++) {  // a second loop is going to check each character of the user text to find a match it to the characters of the first dimension of the encryption array
                if (text.charAt(k) == encryption[1][j]) { // if the chosen character has a match in the first dimension
                    translation[k] = encryption[0][j]; // the new value from the second dimension is assigned to it. The value of the second dimension has the same position that the first dimension character.
                }
            }
        }
        return new String(translation); // Returning a string that stores all the characters from the translation array. That prevents any mistakes passing a value of an array of characters.
    }
}
